All: ContactsApp.class

ContactsApp.class:Contact.java BuisnessContact.java ContactsApp.java
	javac -cp..: .:../lanterna-3.0.0.jar BuisnessContact.java
	javac -cp..: .:../lanterna-3.0.0.jar ContactsApp.java
	
run:
	java -cp ..:.:../lanterna-3.0.0.jar ContactsApp
	java -cp ..:.:../lanterna-3.0.0.jar BuisnessContact
clean:
	rm *.class

